/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./src/components/AppBar.vue')['default']
    Features: typeof import('./src/components/Features.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Packages: typeof import('./src/components/Packages.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VueFooter: typeof import('./src/components/VueFooter.vue')['default']
  }
}
